apiVersion: openbao.apeiro.dev/v1
kind: OpenBaoNamespace
metadata:
  name: my-app-secrets
spec:
  namespace: my-app-secrets
  auth:
    appRole:
      enabled: true
      secretRef:
        name: my-app-approle
        namespace: default
