apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  labels:
    ui.platform-mesh.io/content-for: openbao.apeiro.dev
  name: openbao.apeiro.dev
spec:
  latestResourceSchemas:
  - v260908-5778233.openbaonamespaces.openbao.apeiro.dev
  permissionClaims:
  - all: true
    resource: namespaces
  - all: true
    resource: secrets
  - all: true
    resource: events
  - all: true
    group: core.kcp.io
    resource: logicalclusters
status: {}
