apiVersion: initialization.kcp.io/v1alpha1
kind: InitTemplate
metadata:
  name: openbao-onboarding
spec:
  template: |
    apiVersion: openbao.apeiro.dev/v1
    kind: OpenBaoNamespace
    metadata:
      name: default
    spec:
      auth:
        appRole:
          enabled: true
          secretRef:
            name: openbao-approle-secret
            namespace: default
