apiVersion: v1
kind: Namespace
metadata:
  name: openbao-provider
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-syncagent:openbaotenant-provider
rules:
  - apiGroups:
      - openbao.apeiro.dev
    resources:
      - openbaotenants
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - openbao.apeiro.dev
    resources:
      - openbaotenants/status
    verbs:
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-syncagent:openbaotenant-provider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-syncagent:openbaotenant-provider
subjects:
  - kind: ServiceAccount
    name: openbao-api-syncagent
    namespace: openbao-provider
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao-api-syncagent
  namespace: default
spec:
  chart:
    spec:
      chart: api-syncagent
      version: "0.4.4"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: api-syncagent
  dependsOn:
    - name: api-syncagent
  interval: 1m
  releaseName: openbao-api-syncagent
  targetNamespace: openbao-provider
  timeout: 15m
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    apiExportName: openbao.apeiro.dev
    agentName: openbao-api-syncagent
    publishedResourceSelector: syncagent.kcp.io/agent=openbao-api-syncagent
    kcpKubeconfig: openbao-kubeconfig
    hostAliases:
      enabled: true
      values:
        - ip: "10.96.188.4"
          hostnames:
          - "kcp.api.portal.dev.local"
