apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - helmrepository.yaml
  - helmreleases.yaml
  # bypass OCM resources since local OCI registry is used instead
  #- resources.yaml
