apiVersion: syncagent.kcp.io/v1alpha1
kind: PublishedResource
metadata:
  name: openbaotenant-provider
  labels:
    syncagent.kcp.io/agent: openbao-api-syncagent
spec:
  resource:
    kind: OpenBaoTenant
    apiGroup: openbao.apeiro.dev
    version: v1
  naming:
    name: "{{ .ClusterName }}-{{ .Object.metadata.name | sha3short }}"
  related:
    - identifier: approle-secret
      kind: Secret
      origin: service
      object:
        namespace:
          reference:
            path: spec.auth.appRole.secretRef.namespace
        reference:
          path: spec.auth.appRole.secretRef.name
