{{- if .Values.rbac.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openbao-operator.fullname" . }}-manager-role
  labels:
    {{- include "openbao-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openbao.apeiro.dev
  resources:
  - openbaonamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openbao.apeiro.dev
  resources:
  - openbaonamespaces/finalizers
  verbs:
  - update
- apiGroups:
  - openbao.apeiro.dev
  resources:
  - openbaonamespaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  resourceNames:
  - {{ include "openbao-operator.serviceAccountName" . }}
  verbs:
  - create
- apiGroups:
  - openidclient.keycloak.crossplane.io
  resources:
  - clients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openidgroup.keycloak.crossplane.io
  resources:
  - groupmembershipprotocolmappers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
